### ISSUE TITLE
截图

### ISSUE THREAD

**Issue by WoAiNianChu** [bighammer-link/youth_learnning#4]
可不可以推送截图，主要不想弄那个qq机器人

**Comment by bighammer-link** [comment]
想要截图的话看这个项目：**https://github.com/captain686/Youth-Learning**

**Comment by WoAiNianChu** [comment]
> 想要截图的话看这个项目： **[https://github.com/captain686/Youth-Learning ](https://github.com/captain686/Youth-Learning)**

知道这个项目，主要是不想弄那个机器人

**Comment by bighammer-link** [comment]
> > 想要截图的话看这个项目： **[https://github.com/captain686/Youth-Learning ](https://github.com/captain686/Youth-Learning)**
> 
> 知道这个项目，主要是不想弄那个机器人

他的机器人是做推送用的，获取截图你可以使用其他方式推送啊
